### ISSUE TITLE
Can Clock provide `delta_as_nanos`?

### ISSUE THREAD

**Issue by antifuchs** [metrics-rs/quanta#84]
In governor, I am using a raw nanoseconds representation for quanta readings, which means that every time I take a clock reading, quanta converts nanos into an `std::time::Duration` from a nanos value, which I then convert back. That [costs us quite a bit of performance](https://github.com/antifuchs/governor/pull/175), as well as being so dissatisfyingly close to what I want: You already have the right kind of value, can I just get it without costly conversions? (-:

**Comment by tobz** [comment]
I'm not sure I follow how you're using `Clock`.

If you're already taking raw measurements (`Clock::raw`), then `Clock::delta` already provides the means to get the reference clock-scaled delta back, in the form of `Duration`. Getting the nanosecond measurement from `Duration` is then a const operation: `Duration::as_nanos`.

You only pay the conversion cost once, the same as if you called `Clock::now` and got back `quanta::Instant`.

**Comment by tobz** [comment]
Ah, sorry, right: I had forgotten that `Duration` is holding seconds/fractional nanoseconds. 🤦🏻 

We could probably add `delta_nanos` to skip over the `Duration` conversion entirely. The move to exposing `Instant`/`Duration` was originally to avoid people using the values as implied wall-clock times, the same as `stdlib` does... but since `Duration` can be boiled down to the whole nanoseconds, while `Instant` can never be converted to a wall-clock time... I think we can safely do the same, albeit with new methods.

Might take a few days -- time is sparse for me lately -- but I'm also open to a PR that works as described above.

**Comment by antifuchs** [comment]
OK, that sounds like a good path forward! For `governor`, I was considering making a crate with its nanosecond-scale duration type that's much cheaper to pass around than std Duration, so now might just be the time to do it (or maybe there's one out there already!), I'll go look around if I can find something or publish what I've got.

**Comment by tobz** [comment]
I'd say, generally, I wouldn't be looking to introduce another type to `quanta`, especially one from an external crate. I'd only want to go as far as introducing `Clock::delta_nanos(&self, ...) -> u64` and calling it a day.

**Comment by antifuchs** [comment]
Fair enough! That's an easy change, then (:

**Comment by tobz** [comment]
Closing as this has been long since taken care of.
